ALTER TABLE courts
       ADD created_at TIMESTAMP NOT NULL,
       ADD updated_at TIMESTAMP DEFAULT NULL,
       ADD deleted_at TIMESTAMP DEFAULT NULL;

ALTER TABLE events
    ADD created_at TIMESTAMP NOT NULL,
    ADD updated_at TIMESTAMP DEFAULT NULL,
    ADD deleted_at TIMESTAMP DEFAULT NULL;