version: '3.7'

services:
  app-server:
    build:
      context: basketFinderJava
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/basketFinder?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: basketFinder
      SPRING_DATASOURCE_PASSWORD: basketFinder
    networks:
      - backend
      - frontend
  
  app-client:
    image: bitnami/node
    command: "sh -c 'npm install && npm start'"
    ports:
      - 3000:3000
    volumes:
      - ./basketFinderWeb:/app
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend
  
  db:
    image: mysql:5.7
    ports:
      - 3309:3306
    restart: always
    environment:
      MYSQL_DATABASE: basketFinder
      MYSQL_USER: basketFinder
      MYSQL_PASSWORD: basketFinder
      MYSQL_ROOT_PASSWORD: mysecretpw
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:    