version: '3.7'

services:
  java:
    build: deployment/docker/java
    container_name: basket_finder_java
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    volumes:
      - ./basketFinderJava:/app
    networks:
      - app-tier

  client:
    image: bitnami/node
    command: "sh -c 'npm install && npm start'"
    container_name: basket_finder_react
    ports:
      - 3000:3000
    volumes:
      - ./basketFinderWeb:/app
    restart: always
    networks:
      - app-tier

  postgresql:
    image: bitnami/postgresql:11.5.0
    container_name: basket_finder_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=basketFinder
      - POSTGRESQL_PASSWORD=basketFinder
      - POSTGRESQL_DATABASE=basketFinder
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
