spring:
  datasource:
    url: jdbc:mysql://localhost:3309/basketFinder?useSSL=false
    username: basketFinder
    password: basketFinder

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 11221699996-itunpihiianec1vt13ngh2ku2mbfec81.apps.googleusercontent.com
            clientSecret: vDWt2QzIUl3Cd64aMo7mQ9qs
            redirectUriTemplate: "http://localhost:8080/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      
routes:
  publicRoutes:
    - "/"
    - "/error"
    - "/favicon.ico"
    - "/api/courts/public"
    - "/api/courts/*"
    - "/api/courts/private"
    - "/api/events/court/*"
    - "/api/events/public"
    - "/api/events/private"
    - "/favicon.ico"
    - "/**/*.png"
    - "/**/*.gif"
    - "/**/*.svg"
    - "/**/*.jpg"
    - "/**/*.html"
    - "/**/*.css"
    - "/**/*.js"

google.api.key: AIzaSyCxcxPO50dh9UFCO70A43YI_waCAT0SFBA